name: release

on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/gparch_cli_win64zip
            build/gparch_cli_linux.tar.gz
            build/gparch_cli_macos.zip
